### ISSUE TITLE
안녕하세요. 질문이 있어서 올립니다.

### ISSUE THREAD

**Issue by kimyoungjin06** [jupyternims/docker-image#1]
한양대학교 응용물리학과의 김영진입니다.
예전에 성욱이를 통해 한 번 질문 드린 적이 있는데요.
우선 서버를 잘 이용하고있습니다.

저희도 이번에 저희 서버를 한 번 비슷한 환경으로 세팅을 하려하는데,
우측 상단에 hosted by <icon> 이건 어떻게 넣은건지 궁금합니다...

**Comment by wizardbc** [comment]
`/opt/conda/lib/python3.6/site-packages/notebook/templates/` 디렉토리를 수정하거나

jupyter 설정파일에
```
c.NotebookApp.extra_template_paths = ['/srv/templates/']
```
와 같이 template 파일을 저장할 디렉토리를 설정하면 됩니다.

[jupyter/docker-demo-images](https://github.com/jupyter/docker-demo-images) 의 `Dockerfile` 과 `/resources/` 디렉토리를 참고하세요.

W12aRd :)
