### ISSUE TITLE
Julia 0.6로 업그레이드 건의

### ISSUE THREAD

**Issue by appleparan** [jupyternims/docker-image#2]
Julia Kernel이 0.5.2로 설치되어있는데, 혹시 0.6으로 업그레이드 가능할까요?

Data Science Notebook에는 0.5.2로 깔려있기는 한데, Julia 가 버전 한번 올라갈 때마다 변경점들이 많아서
 0.5.2면 상당히 구버전이라고 생각됩니다.  

[Docker hub](https://hub.docker.com/r/staticfloat/julia/) 참고하셔 되고 위 docker hub 이미지용 [스크립트](https://github.com/staticfloat/julia-docker/tree/master/julia)도 참고하셔도 될 것 같습니다. 감사합니다.

**Comment by wizardbc** [comment]
Data Science Notebook 에서 제공하는 커널을 개별적으로 업데이트 할 예정은 없습니다.

이 이미지는 Data Science Notebook 에 수학자들이 필요로하는 커널 (sagemath, octave 등)을 추가하는 방향으로 관리되고 있습니다.

Data Science Notebook 자체를 개선하거나, 포함된 커널을 업데이트 하는 문제는 [jupyter/docker-stacks](https://github.com/jupyter/docker-stacks) 쪽에 이슈를 넣어보시는게 좋을것 같습니다.
