### ISSUE TITLE
만족스럽습니다.

### ISSUE THREAD

**Issue by kimmingul** [jupyternims/docker-image#3]
우연히 알게되었는데, 매우 만족스럽습니다.

**Comment by wizardbc** [comment]
감사합니다.
바로 사용할 수 있는 all-in-one 이미지를 추구하고 있습니다.
가벼운 이미지를 추구하는  [jupyter/docker-stacks](https://github.com/jupyter/docker-stacks) 도 방문해 보세요. ^^

W12aRd :)
