### ISSUE TITLE
500 : Internal Server Error

### ISSUE THREAD

**Issue by partrita** [jupyternims/docker-image#4]
500 : Internal Server Error
Redirect loop detected.

You can try restarting your server from the home page.

접속시 internal sever error가 나는데, 해결방법이 없을까요?
오랫동안 잘쓰고있었는데, 백업도 안해둔상태에서 이런일이 생기네요

**Comment by wizardbc** [comment]
서버를 재부팅하였습니다.

**Comment by partrita** [comment]
감사합니다ㅎ
